language: node_js
node_js:
  - 6

cache:
  directories:
  - node_modules

before_install:
  - npm install codecov.io coveralls

script:
  - npm test
  - npm run build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false

branches:
  only:
    - master
